// Generated by scripts/generate-session-events.mjs.
// Source: vendor/copilot/schemas/session-events.schema.json
// Schema sha256: ce6ea924e8bd3cb825046d7328a4b0922d787efa9868f9e7816df95e1ab2b545
// Discriminators: 140
// Regenerate with: node scripts/generate-session-events.mjs

const std = @import("std");
const payloads = @import("session_event_payloads.zig");

pub const SessionEvent = union(enum) {
    abort: payloads.RawEvent,
    agent_interrupted: payloads.RawEvent,
    assistant_fusion_phase_activity: payloads.RawEvent,
    assistant_fusion_phase_completed: payloads.RawEvent,
    assistant_fusion_phase_failed: payloads.RawEvent,
    assistant_fusion_phase_started: payloads.RawEvent,
    assistant_idle: payloads.RawEvent,
    assistant_intent: payloads.RawEvent,
    assistant_message: payloads.AssistantMessage,
    assistant_message_delta: payloads.AssistantMessageDelta,
    assistant_message_start: payloads.RawEvent,
    assistant_reasoning: payloads.AssistantReasoning,
    assistant_reasoning_delta: payloads.AssistantReasoningDelta,
    assistant_server_tool_progress: payloads.RawEvent,
    assistant_streaming_delta: payloads.RawEvent,
    assistant_tool_call_delta: payloads.RawEvent,
    assistant_turn_end: payloads.RawEvent,
    assistant_turn_retry: payloads.RawEvent,
    assistant_turn_start: payloads.RawEvent,
    assistant_usage: payloads.RawEvent,
    auto_mode_switch_completed: payloads.RawEvent,
    auto_mode_switch_requested: payloads.RawEvent,
    capabilities_changed: payloads.RawEvent,
    command_completed: payloads.RawEvent,
    command_execute: payloads.RawEvent,
    command_queued: payloads.RawEvent,
    commands_changed: payloads.RawEvent,
    elicitation_completed: payloads.RawEvent,
    elicitation_requested: payloads.RawEvent,
    exit_plan_mode_completed: payloads.RawEvent,
    exit_plan_mode_requested: payloads.RawEvent,
    external_tool_completed: payloads.RawEvent,
    external_tool_requested: payloads.ExternalToolRequested,
    factory_run_settled: payloads.RawEvent,
    factory_run_started: payloads.RawEvent,
    factory_run_updated: payloads.RawEvent,
    hook_end: payloads.RawEvent,
    hook_progress: payloads.RawEvent,
    hook_start: payloads.RawEvent,
    mcp_headers_refresh_completed: payloads.RawEvent,
    mcp_headers_refresh_required: payloads.RawEvent,
    mcp_oauth_completed: payloads.RawEvent,
    mcp_oauth_required: payloads.RawEvent,
    mcp_prompts_list_changed: payloads.RawEvent,
    mcp_resources_list_changed: payloads.RawEvent,
    mcp_tools_list_changed: payloads.RawEvent,
    mcp_app_tool_call_complete: payloads.RawEvent,
    model_call_failure: payloads.RawEvent,
    model_call_finished: payloads.RawEvent,
    model_call_start: payloads.RawEvent,
    pending_messages_modified: payloads.RawEvent,
    permission_completed: payloads.RawEvent,
    permission_requested: payloads.PermissionRequested,
    prompt_cache_break: payloads.RawEvent,
    sampling_completed: payloads.RawEvent,
    sampling_requested: payloads.RawEvent,
    sandbox_decision: payloads.RawEvent,
    session_auto_mode_resolved: payloads.RawEvent,
    session_auto_tier_recommendation: payloads.RawEvent,
    session_auto_tier_switch_failed: payloads.RawEvent,
    session_autopilot_objective_changed: payloads.RawEvent,
    session_background_tasks_changed: payloads.RawEvent,
    session_binary_asset: payloads.RawEvent,
    session_canvas_closed: payloads.RawEvent,
    session_canvas_opened: payloads.RawEvent,
    session_canvas_recorded: payloads.RawEvent,
    session_canvas_registry_changed: payloads.RawEvent,
    session_canvas_removed: payloads.RawEvent,
    session_canvas_unavailable: payloads.RawEvent,
    session_compaction_complete: payloads.RawEvent,
    session_compaction_start: payloads.RawEvent,
    session_completion_receipt: payloads.RawEvent,
    session_context_changed: payloads.RawEvent,
    session_context_cleared: payloads.RawEvent,
    session_custom_agents_updated: payloads.RawEvent,
    session_custom_notification: payloads.RawEvent,
    session_error: payloads.SessionError,
    session_extensions_attachments_pushed: payloads.RawEvent,
    session_extensions_loaded: payloads.RawEvent,
    session_fusion_commit_started: payloads.RawEvent,
    session_fusion_completed: payloads.RawEvent,
    session_fusion_handoff: payloads.RawEvent,
    session_fusion_resolved: payloads.RawEvent,
    session_fusion_route_failed: payloads.RawEvent,
    session_fusion_route_started: payloads.RawEvent,
    session_handoff: payloads.RawEvent,
    session_idle: payloads.SessionIdle,
    session_info: payloads.RawEvent,
    session_managed_settings_enforced: payloads.RawEvent,
    session_managed_settings_resolved: payloads.RawEvent,
    session_mcp_server_needs_reconnect: payloads.RawEvent,
    session_mcp_server_removed: payloads.RawEvent,
    session_mcp_server_status_changed: payloads.RawEvent,
    session_mcp_servers_loaded: payloads.RawEvent,
    session_memory_changed: payloads.RawEvent,
    session_mode_changed: payloads.RawEvent,
    session_mode_notice_delivered: payloads.RawEvent,
    session_model_change: payloads.RawEvent,
    session_permissions_changed: payloads.RawEvent,
    session_plan_changed: payloads.RawEvent,
    session_remote_steerable_changed: payloads.RawEvent,
    session_resume: payloads.RawEvent,
    session_schedule_cancelled: payloads.RawEvent,
    session_schedule_created: payloads.RawEvent,
    session_schedule_rearmed: payloads.RawEvent,
    session_session_limits_changed: payloads.RawEvent,
    session_shutdown: payloads.RawEvent,
    session_skills_loaded: payloads.RawEvent,
    session_snapshot_rewind: payloads.RawEvent,
    session_start: payloads.RawEvent,
    session_task_complete: payloads.RawEvent,
    session_title_changed: payloads.RawEvent,
    session_todos_changed: payloads.RawEvent,
    session_tools_updated: payloads.RawEvent,
    session_truncation: payloads.RawEvent,
    session_usage_checkpoint: payloads.RawEvent,
    session_usage_info: payloads.RawEvent,
    session_warning: payloads.RawEvent,
    session_workspace_file_changed: payloads.RawEvent,
    session_limits_exhausted_completed: payloads.RawEvent,
    session_limits_exhausted_requested: payloads.RawEvent,
    skill_invoked: payloads.RawEvent,
    subagent_completed: payloads.RawEvent,
    subagent_configured: payloads.RawEvent,
    subagent_deselected: payloads.RawEvent,
    subagent_failed: payloads.RawEvent,
    subagent_selected: payloads.RawEvent,
    subagent_started: payloads.RawEvent,
    system_message: payloads.RawEvent,
    system_notification: payloads.RawEvent,
    tool_execution_complete: payloads.RawEvent,
    tool_execution_partial_result: payloads.RawEvent,
    tool_execution_progress: payloads.RawEvent,
    tool_execution_start: payloads.RawEvent,
    tool_user_requested: payloads.RawEvent,
    tool_search_activated: payloads.RawEvent,
    ui_ephemeral_query: payloads.RawEvent,
    user_message: payloads.RawEvent,
    user_input_completed: payloads.RawEvent,
    user_input_requested: payloads.RawEvent,
    unknown: payloads.UnknownEvent,

    pub fn eventType(self: SessionEvent) []const u8 {
        return switch (self) {
            .abort => "abort",
            .agent_interrupted => "agent.interrupted",
            .assistant_fusion_phase_activity => "assistant.fusion_phase_activity",
            .assistant_fusion_phase_completed => "assistant.fusion_phase_completed",
            .assistant_fusion_phase_failed => "assistant.fusion_phase_failed",
            .assistant_fusion_phase_started => "assistant.fusion_phase_started",
            .assistant_idle => "assistant.idle",
            .assistant_intent => "assistant.intent",
            .assistant_message => "assistant.message",
            .assistant_message_delta => "assistant.message_delta",
            .assistant_message_start => "assistant.message_start",
            .assistant_reasoning => "assistant.reasoning",
            .assistant_reasoning_delta => "assistant.reasoning_delta",
            .assistant_server_tool_progress => "assistant.server_tool_progress",
            .assistant_streaming_delta => "assistant.streaming_delta",
            .assistant_tool_call_delta => "assistant.tool_call_delta",
            .assistant_turn_end => "assistant.turn_end",
            .assistant_turn_retry => "assistant.turn_retry",
            .assistant_turn_start => "assistant.turn_start",
            .assistant_usage => "assistant.usage",
            .auto_mode_switch_completed => "auto_mode_switch.completed",
            .auto_mode_switch_requested => "auto_mode_switch.requested",
            .capabilities_changed => "capabilities.changed",
            .command_completed => "command.completed",
            .command_execute => "command.execute",
            .command_queued => "command.queued",
            .commands_changed => "commands.changed",
            .elicitation_completed => "elicitation.completed",
            .elicitation_requested => "elicitation.requested",
            .exit_plan_mode_completed => "exit_plan_mode.completed",
            .exit_plan_mode_requested => "exit_plan_mode.requested",
            .external_tool_completed => "external_tool.completed",
            .external_tool_requested => "external_tool.requested",
            .factory_run_settled => "factory.run_settled",
            .factory_run_started => "factory.run_started",
            .factory_run_updated => "factory.run_updated",
            .hook_end => "hook.end",
            .hook_progress => "hook.progress",
            .hook_start => "hook.start",
            .mcp_headers_refresh_completed => "mcp.headers_refresh_completed",
            .mcp_headers_refresh_required => "mcp.headers_refresh_required",
            .mcp_oauth_completed => "mcp.oauth_completed",
            .mcp_oauth_required => "mcp.oauth_required",
            .mcp_prompts_list_changed => "mcp.prompts.list_changed",
            .mcp_resources_list_changed => "mcp.resources.list_changed",
            .mcp_tools_list_changed => "mcp.tools.list_changed",
            .mcp_app_tool_call_complete => "mcp_app.tool_call_complete",
            .model_call_failure => "model.call_failure",
            .model_call_finished => "model.call_finished",
            .model_call_start => "model.call_start",
            .pending_messages_modified => "pending_messages.modified",
            .permission_completed => "permission.completed",
            .permission_requested => "permission.requested",
            .prompt_cache_break => "prompt_cache_break",
            .sampling_completed => "sampling.completed",
            .sampling_requested => "sampling.requested",
            .sandbox_decision => "sandbox.decision",
            .session_auto_mode_resolved => "session.auto_mode_resolved",
            .session_auto_tier_recommendation => "session.auto_tier_recommendation",
            .session_auto_tier_switch_failed => "session.auto_tier_switch_failed",
            .session_autopilot_objective_changed => "session.autopilot_objective_changed",
            .session_background_tasks_changed => "session.background_tasks_changed",
            .session_binary_asset => "session.binary_asset",
            .session_canvas_closed => "session.canvas.closed",
            .session_canvas_opened => "session.canvas.opened",
            .session_canvas_recorded => "session.canvas.recorded",
            .session_canvas_registry_changed => "session.canvas.registry_changed",
            .session_canvas_removed => "session.canvas.removed",
            .session_canvas_unavailable => "session.canvas.unavailable",
            .session_compaction_complete => "session.compaction_complete",
            .session_compaction_start => "session.compaction_start",
            .session_completion_receipt => "session.completion_receipt",
            .session_context_changed => "session.context_changed",
            .session_context_cleared => "session.context_cleared",
            .session_custom_agents_updated => "session.custom_agents_updated",
            .session_custom_notification => "session.custom_notification",
            .session_error => "session.error",
            .session_extensions_attachments_pushed => "session.extensions.attachments_pushed",
            .session_extensions_loaded => "session.extensions_loaded",
            .session_fusion_commit_started => "session.fusion_commit_started",
            .session_fusion_completed => "session.fusion_completed",
            .session_fusion_handoff => "session.fusion_handoff",
            .session_fusion_resolved => "session.fusion_resolved",
            .session_fusion_route_failed => "session.fusion_route_failed",
            .session_fusion_route_started => "session.fusion_route_started",
            .session_handoff => "session.handoff",
            .session_idle => "session.idle",
            .session_info => "session.info",
            .session_managed_settings_enforced => "session.managed_settings_enforced",
            .session_managed_settings_resolved => "session.managed_settings_resolved",
            .session_mcp_server_needs_reconnect => "session.mcp_server_needs_reconnect",
            .session_mcp_server_removed => "session.mcp_server_removed",
            .session_mcp_server_status_changed => "session.mcp_server_status_changed",
            .session_mcp_servers_loaded => "session.mcp_servers_loaded",
            .session_memory_changed => "session.memory_changed",
            .session_mode_changed => "session.mode_changed",
            .session_mode_notice_delivered => "session.mode_notice_delivered",
            .session_model_change => "session.model_change",
            .session_permissions_changed => "session.permissions_changed",
            .session_plan_changed => "session.plan_changed",
            .session_remote_steerable_changed => "session.remote_steerable_changed",
            .session_resume => "session.resume",
            .session_schedule_cancelled => "session.schedule_cancelled",
            .session_schedule_created => "session.schedule_created",
            .session_schedule_rearmed => "session.schedule_rearmed",
            .session_session_limits_changed => "session.session_limits_changed",
            .session_shutdown => "session.shutdown",
            .session_skills_loaded => "session.skills_loaded",
            .session_snapshot_rewind => "session.snapshot_rewind",
            .session_start => "session.start",
            .session_task_complete => "session.task_complete",
            .session_title_changed => "session.title_changed",
            .session_todos_changed => "session.todos_changed",
            .session_tools_updated => "session.tools_updated",
            .session_truncation => "session.truncation",
            .session_usage_checkpoint => "session.usage_checkpoint",
            .session_usage_info => "session.usage_info",
            .session_warning => "session.warning",
            .session_workspace_file_changed => "session.workspace_file_changed",
            .session_limits_exhausted_completed => "session_limits_exhausted.completed",
            .session_limits_exhausted_requested => "session_limits_exhausted.requested",
            .skill_invoked => "skill.invoked",
            .subagent_completed => "subagent.completed",
            .subagent_configured => "subagent.configured",
            .subagent_deselected => "subagent.deselected",
            .subagent_failed => "subagent.failed",
            .subagent_selected => "subagent.selected",
            .subagent_started => "subagent.started",
            .system_message => "system.message",
            .system_notification => "system.notification",
            .tool_execution_complete => "tool.execution_complete",
            .tool_execution_partial_result => "tool.execution_partial_result",
            .tool_execution_progress => "tool.execution_progress",
            .tool_execution_start => "tool.execution_start",
            .tool_user_requested => "tool.user_requested",
            .tool_search_activated => "tool_search.activated",
            .ui_ephemeral_query => "ui.ephemeral_query",
            .user_message => "user.message",
            .user_input_completed => "user_input.completed",
            .user_input_requested => "user_input.requested",
            .unknown => |value| value.event_type,
        };
    }

    pub fn rawData(self: SessionEvent) []const u8 {
        return switch (self) {
            .abort => |value| value.data_json,
            .agent_interrupted => |value| value.data_json,
            .assistant_fusion_phase_activity => |value| value.data_json,
            .assistant_fusion_phase_completed => |value| value.data_json,
            .assistant_fusion_phase_failed => |value| value.data_json,
            .assistant_fusion_phase_started => |value| value.data_json,
            .assistant_idle => |value| value.data_json,
            .assistant_intent => |value| value.data_json,
            .assistant_message => |value| value.raw.data_json,
            .assistant_message_delta => |value| value.raw.data_json,
            .assistant_message_start => |value| value.data_json,
            .assistant_reasoning => |value| value.raw.data_json,
            .assistant_reasoning_delta => |value| value.raw.data_json,
            .assistant_server_tool_progress => |value| value.data_json,
            .assistant_streaming_delta => |value| value.data_json,
            .assistant_tool_call_delta => |value| value.data_json,
            .assistant_turn_end => |value| value.data_json,
            .assistant_turn_retry => |value| value.data_json,
            .assistant_turn_start => |value| value.data_json,
            .assistant_usage => |value| value.data_json,
            .auto_mode_switch_completed => |value| value.data_json,
            .auto_mode_switch_requested => |value| value.data_json,
            .capabilities_changed => |value| value.data_json,
            .command_completed => |value| value.data_json,
            .command_execute => |value| value.data_json,
            .command_queued => |value| value.data_json,
            .commands_changed => |value| value.data_json,
            .elicitation_completed => |value| value.data_json,
            .elicitation_requested => |value| value.data_json,
            .exit_plan_mode_completed => |value| value.data_json,
            .exit_plan_mode_requested => |value| value.data_json,
            .external_tool_completed => |value| value.data_json,
            .external_tool_requested => |value| value.raw.data_json,
            .factory_run_settled => |value| value.data_json,
            .factory_run_started => |value| value.data_json,
            .factory_run_updated => |value| value.data_json,
            .hook_end => |value| value.data_json,
            .hook_progress => |value| value.data_json,
            .hook_start => |value| value.data_json,
            .mcp_headers_refresh_completed => |value| value.data_json,
            .mcp_headers_refresh_required => |value| value.data_json,
            .mcp_oauth_completed => |value| value.data_json,
            .mcp_oauth_required => |value| value.data_json,
            .mcp_prompts_list_changed => |value| value.data_json,
            .mcp_resources_list_changed => |value| value.data_json,
            .mcp_tools_list_changed => |value| value.data_json,
            .mcp_app_tool_call_complete => |value| value.data_json,
            .model_call_failure => |value| value.data_json,
            .model_call_finished => |value| value.data_json,
            .model_call_start => |value| value.data_json,
            .pending_messages_modified => |value| value.data_json,
            .permission_completed => |value| value.data_json,
            .permission_requested => |value| value.raw.data_json,
            .prompt_cache_break => |value| value.data_json,
            .sampling_completed => |value| value.data_json,
            .sampling_requested => |value| value.data_json,
            .sandbox_decision => |value| value.data_json,
            .session_auto_mode_resolved => |value| value.data_json,
            .session_auto_tier_recommendation => |value| value.data_json,
            .session_auto_tier_switch_failed => |value| value.data_json,
            .session_autopilot_objective_changed => |value| value.data_json,
            .session_background_tasks_changed => |value| value.data_json,
            .session_binary_asset => |value| value.data_json,
            .session_canvas_closed => |value| value.data_json,
            .session_canvas_opened => |value| value.data_json,
            .session_canvas_recorded => |value| value.data_json,
            .session_canvas_registry_changed => |value| value.data_json,
            .session_canvas_removed => |value| value.data_json,
            .session_canvas_unavailable => |value| value.data_json,
            .session_compaction_complete => |value| value.data_json,
            .session_compaction_start => |value| value.data_json,
            .session_completion_receipt => |value| value.data_json,
            .session_context_changed => |value| value.data_json,
            .session_context_cleared => |value| value.data_json,
            .session_custom_agents_updated => |value| value.data_json,
            .session_custom_notification => |value| value.data_json,
            .session_error => |value| value.raw.data_json,
            .session_extensions_attachments_pushed => |value| value.data_json,
            .session_extensions_loaded => |value| value.data_json,
            .session_fusion_commit_started => |value| value.data_json,
            .session_fusion_completed => |value| value.data_json,
            .session_fusion_handoff => |value| value.data_json,
            .session_fusion_resolved => |value| value.data_json,
            .session_fusion_route_failed => |value| value.data_json,
            .session_fusion_route_started => |value| value.data_json,
            .session_handoff => |value| value.data_json,
            .session_idle => |value| value.raw.data_json,
            .session_info => |value| value.data_json,
            .session_managed_settings_enforced => |value| value.data_json,
            .session_managed_settings_resolved => |value| value.data_json,
            .session_mcp_server_needs_reconnect => |value| value.data_json,
            .session_mcp_server_removed => |value| value.data_json,
            .session_mcp_server_status_changed => |value| value.data_json,
            .session_mcp_servers_loaded => |value| value.data_json,
            .session_memory_changed => |value| value.data_json,
            .session_mode_changed => |value| value.data_json,
            .session_mode_notice_delivered => |value| value.data_json,
            .session_model_change => |value| value.data_json,
            .session_permissions_changed => |value| value.data_json,
            .session_plan_changed => |value| value.data_json,
            .session_remote_steerable_changed => |value| value.data_json,
            .session_resume => |value| value.data_json,
            .session_schedule_cancelled => |value| value.data_json,
            .session_schedule_created => |value| value.data_json,
            .session_schedule_rearmed => |value| value.data_json,
            .session_session_limits_changed => |value| value.data_json,
            .session_shutdown => |value| value.data_json,
            .session_skills_loaded => |value| value.data_json,
            .session_snapshot_rewind => |value| value.data_json,
            .session_start => |value| value.data_json,
            .session_task_complete => |value| value.data_json,
            .session_title_changed => |value| value.data_json,
            .session_todos_changed => |value| value.data_json,
            .session_tools_updated => |value| value.data_json,
            .session_truncation => |value| value.data_json,
            .session_usage_checkpoint => |value| value.data_json,
            .session_usage_info => |value| value.data_json,
            .session_warning => |value| value.data_json,
            .session_workspace_file_changed => |value| value.data_json,
            .session_limits_exhausted_completed => |value| value.data_json,
            .session_limits_exhausted_requested => |value| value.data_json,
            .skill_invoked => |value| value.data_json,
            .subagent_completed => |value| value.data_json,
            .subagent_configured => |value| value.data_json,
            .subagent_deselected => |value| value.data_json,
            .subagent_failed => |value| value.data_json,
            .subagent_selected => |value| value.data_json,
            .subagent_started => |value| value.data_json,
            .system_message => |value| value.data_json,
            .system_notification => |value| value.data_json,
            .tool_execution_complete => |value| value.data_json,
            .tool_execution_partial_result => |value| value.data_json,
            .tool_execution_progress => |value| value.data_json,
            .tool_execution_start => |value| value.data_json,
            .tool_user_requested => |value| value.data_json,
            .tool_search_activated => |value| value.data_json,
            .ui_ephemeral_query => |value| value.data_json,
            .user_message => |value| value.data_json,
            .user_input_completed => |value| value.data_json,
            .user_input_requested => |value| value.data_json,
            .unknown => |value| value.data_json,
        };
    }

    pub fn deinit(self: *SessionEvent, allocator: std.mem.Allocator) void {
        switch (self.*) {
            .abort => |*value| value.deinit(allocator),
            .agent_interrupted => |*value| value.deinit(allocator),
            .assistant_fusion_phase_activity => |*value| value.deinit(allocator),
            .assistant_fusion_phase_completed => |*value| value.deinit(allocator),
            .assistant_fusion_phase_failed => |*value| value.deinit(allocator),
            .assistant_fusion_phase_started => |*value| value.deinit(allocator),
            .assistant_idle => |*value| value.deinit(allocator),
            .assistant_intent => |*value| value.deinit(allocator),
            .assistant_message => |*value| value.deinit(allocator),
            .assistant_message_delta => |*value| value.deinit(allocator),
            .assistant_message_start => |*value| value.deinit(allocator),
            .assistant_reasoning => |*value| value.deinit(allocator),
            .assistant_reasoning_delta => |*value| value.deinit(allocator),
            .assistant_server_tool_progress => |*value| value.deinit(allocator),
            .assistant_streaming_delta => |*value| value.deinit(allocator),
            .assistant_tool_call_delta => |*value| value.deinit(allocator),
            .assistant_turn_end => |*value| value.deinit(allocator),
            .assistant_turn_retry => |*value| value.deinit(allocator),
            .assistant_turn_start => |*value| value.deinit(allocator),
            .assistant_usage => |*value| value.deinit(allocator),
            .auto_mode_switch_completed => |*value| value.deinit(allocator),
            .auto_mode_switch_requested => |*value| value.deinit(allocator),
            .capabilities_changed => |*value| value.deinit(allocator),
            .command_completed => |*value| value.deinit(allocator),
            .command_execute => |*value| value.deinit(allocator),
            .command_queued => |*value| value.deinit(allocator),
            .commands_changed => |*value| value.deinit(allocator),
            .elicitation_completed => |*value| value.deinit(allocator),
            .elicitation_requested => |*value| value.deinit(allocator),
            .exit_plan_mode_completed => |*value| value.deinit(allocator),
            .exit_plan_mode_requested => |*value| value.deinit(allocator),
            .external_tool_completed => |*value| value.deinit(allocator),
            .external_tool_requested => |*value| value.deinit(allocator),
            .factory_run_settled => |*value| value.deinit(allocator),
            .factory_run_started => |*value| value.deinit(allocator),
            .factory_run_updated => |*value| value.deinit(allocator),
            .hook_end => |*value| value.deinit(allocator),
            .hook_progress => |*value| value.deinit(allocator),
            .hook_start => |*value| value.deinit(allocator),
            .mcp_headers_refresh_completed => |*value| value.deinit(allocator),
            .mcp_headers_refresh_required => |*value| value.deinit(allocator),
            .mcp_oauth_completed => |*value| value.deinit(allocator),
            .mcp_oauth_required => |*value| value.deinit(allocator),
            .mcp_prompts_list_changed => |*value| value.deinit(allocator),
            .mcp_resources_list_changed => |*value| value.deinit(allocator),
            .mcp_tools_list_changed => |*value| value.deinit(allocator),
            .mcp_app_tool_call_complete => |*value| value.deinit(allocator),
            .model_call_failure => |*value| value.deinit(allocator),
            .model_call_finished => |*value| value.deinit(allocator),
            .model_call_start => |*value| value.deinit(allocator),
            .pending_messages_modified => |*value| value.deinit(allocator),
            .permission_completed => |*value| value.deinit(allocator),
            .permission_requested => |*value| value.deinit(allocator),
            .prompt_cache_break => |*value| value.deinit(allocator),
            .sampling_completed => |*value| value.deinit(allocator),
            .sampling_requested => |*value| value.deinit(allocator),
            .sandbox_decision => |*value| value.deinit(allocator),
            .session_auto_mode_resolved => |*value| value.deinit(allocator),
            .session_auto_tier_recommendation => |*value| value.deinit(allocator),
            .session_auto_tier_switch_failed => |*value| value.deinit(allocator),
            .session_autopilot_objective_changed => |*value| value.deinit(allocator),
            .session_background_tasks_changed => |*value| value.deinit(allocator),
            .session_binary_asset => |*value| value.deinit(allocator),
            .session_canvas_closed => |*value| value.deinit(allocator),
            .session_canvas_opened => |*value| value.deinit(allocator),
            .session_canvas_recorded => |*value| value.deinit(allocator),
            .session_canvas_registry_changed => |*value| value.deinit(allocator),
            .session_canvas_removed => |*value| value.deinit(allocator),
            .session_canvas_unavailable => |*value| value.deinit(allocator),
            .session_compaction_complete => |*value| value.deinit(allocator),
            .session_compaction_start => |*value| value.deinit(allocator),
            .session_completion_receipt => |*value| value.deinit(allocator),
            .session_context_changed => |*value| value.deinit(allocator),
            .session_context_cleared => |*value| value.deinit(allocator),
            .session_custom_agents_updated => |*value| value.deinit(allocator),
            .session_custom_notification => |*value| value.deinit(allocator),
            .session_error => |*value| value.deinit(allocator),
            .session_extensions_attachments_pushed => |*value| value.deinit(allocator),
            .session_extensions_loaded => |*value| value.deinit(allocator),
            .session_fusion_commit_started => |*value| value.deinit(allocator),
            .session_fusion_completed => |*value| value.deinit(allocator),
            .session_fusion_handoff => |*value| value.deinit(allocator),
            .session_fusion_resolved => |*value| value.deinit(allocator),
            .session_fusion_route_failed => |*value| value.deinit(allocator),
            .session_fusion_route_started => |*value| value.deinit(allocator),
            .session_handoff => |*value| value.deinit(allocator),
            .session_idle => |*value| value.deinit(allocator),
            .session_info => |*value| value.deinit(allocator),
            .session_managed_settings_enforced => |*value| value.deinit(allocator),
            .session_managed_settings_resolved => |*value| value.deinit(allocator),
            .session_mcp_server_needs_reconnect => |*value| value.deinit(allocator),
            .session_mcp_server_removed => |*value| value.deinit(allocator),
            .session_mcp_server_status_changed => |*value| value.deinit(allocator),
            .session_mcp_servers_loaded => |*value| value.deinit(allocator),
            .session_memory_changed => |*value| value.deinit(allocator),
            .session_mode_changed => |*value| value.deinit(allocator),
            .session_mode_notice_delivered => |*value| value.deinit(allocator),
            .session_model_change => |*value| value.deinit(allocator),
            .session_permissions_changed => |*value| value.deinit(allocator),
            .session_plan_changed => |*value| value.deinit(allocator),
            .session_remote_steerable_changed => |*value| value.deinit(allocator),
            .session_resume => |*value| value.deinit(allocator),
            .session_schedule_cancelled => |*value| value.deinit(allocator),
            .session_schedule_created => |*value| value.deinit(allocator),
            .session_schedule_rearmed => |*value| value.deinit(allocator),
            .session_session_limits_changed => |*value| value.deinit(allocator),
            .session_shutdown => |*value| value.deinit(allocator),
            .session_skills_loaded => |*value| value.deinit(allocator),
            .session_snapshot_rewind => |*value| value.deinit(allocator),
            .session_start => |*value| value.deinit(allocator),
            .session_task_complete => |*value| value.deinit(allocator),
            .session_title_changed => |*value| value.deinit(allocator),
            .session_todos_changed => |*value| value.deinit(allocator),
            .session_tools_updated => |*value| value.deinit(allocator),
            .session_truncation => |*value| value.deinit(allocator),
            .session_usage_checkpoint => |*value| value.deinit(allocator),
            .session_usage_info => |*value| value.deinit(allocator),
            .session_warning => |*value| value.deinit(allocator),
            .session_workspace_file_changed => |*value| value.deinit(allocator),
            .session_limits_exhausted_completed => |*value| value.deinit(allocator),
            .session_limits_exhausted_requested => |*value| value.deinit(allocator),
            .skill_invoked => |*value| value.deinit(allocator),
            .subagent_completed => |*value| value.deinit(allocator),
            .subagent_configured => |*value| value.deinit(allocator),
            .subagent_deselected => |*value| value.deinit(allocator),
            .subagent_failed => |*value| value.deinit(allocator),
            .subagent_selected => |*value| value.deinit(allocator),
            .subagent_started => |*value| value.deinit(allocator),
            .system_message => |*value| value.deinit(allocator),
            .system_notification => |*value| value.deinit(allocator),
            .tool_execution_complete => |*value| value.deinit(allocator),
            .tool_execution_partial_result => |*value| value.deinit(allocator),
            .tool_execution_progress => |*value| value.deinit(allocator),
            .tool_execution_start => |*value| value.deinit(allocator),
            .tool_user_requested => |*value| value.deinit(allocator),
            .tool_search_activated => |*value| value.deinit(allocator),
            .ui_ephemeral_query => |*value| value.deinit(allocator),
            .user_message => |*value| value.deinit(allocator),
            .user_input_completed => |*value| value.deinit(allocator),
            .user_input_requested => |*value| value.deinit(allocator),
            .unknown => |*value| value.deinit(allocator),
        }
    }
};

pub const SessionEventTag = std.meta.Tag(SessionEvent);

pub const RegistryEntry = struct {
    wire: []const u8,
    tag: SessionEventTag,
};

pub const pinned_discriminators = [_]RegistryEntry{
    .{ .wire = "abort", .tag = .abort },
    .{ .wire = "agent.interrupted", .tag = .agent_interrupted },
    .{ .wire = "assistant.fusion_phase_activity", .tag = .assistant_fusion_phase_activity },
    .{ .wire = "assistant.fusion_phase_completed", .tag = .assistant_fusion_phase_completed },
    .{ .wire = "assistant.fusion_phase_failed", .tag = .assistant_fusion_phase_failed },
    .{ .wire = "assistant.fusion_phase_started", .tag = .assistant_fusion_phase_started },
    .{ .wire = "assistant.idle", .tag = .assistant_idle },
    .{ .wire = "assistant.intent", .tag = .assistant_intent },
    .{ .wire = "assistant.message", .tag = .assistant_message },
    .{ .wire = "assistant.message_delta", .tag = .assistant_message_delta },
    .{ .wire = "assistant.message_start", .tag = .assistant_message_start },
    .{ .wire = "assistant.reasoning", .tag = .assistant_reasoning },
    .{ .wire = "assistant.reasoning_delta", .tag = .assistant_reasoning_delta },
    .{ .wire = "assistant.server_tool_progress", .tag = .assistant_server_tool_progress },
    .{ .wire = "assistant.streaming_delta", .tag = .assistant_streaming_delta },
    .{ .wire = "assistant.tool_call_delta", .tag = .assistant_tool_call_delta },
    .{ .wire = "assistant.turn_end", .tag = .assistant_turn_end },
    .{ .wire = "assistant.turn_retry", .tag = .assistant_turn_retry },
    .{ .wire = "assistant.turn_start", .tag = .assistant_turn_start },
    .{ .wire = "assistant.usage", .tag = .assistant_usage },
    .{ .wire = "auto_mode_switch.completed", .tag = .auto_mode_switch_completed },
    .{ .wire = "auto_mode_switch.requested", .tag = .auto_mode_switch_requested },
    .{ .wire = "capabilities.changed", .tag = .capabilities_changed },
    .{ .wire = "command.completed", .tag = .command_completed },
    .{ .wire = "command.execute", .tag = .command_execute },
    .{ .wire = "command.queued", .tag = .command_queued },
    .{ .wire = "commands.changed", .tag = .commands_changed },
    .{ .wire = "elicitation.completed", .tag = .elicitation_completed },
    .{ .wire = "elicitation.requested", .tag = .elicitation_requested },
    .{ .wire = "exit_plan_mode.completed", .tag = .exit_plan_mode_completed },
    .{ .wire = "exit_plan_mode.requested", .tag = .exit_plan_mode_requested },
    .{ .wire = "external_tool.completed", .tag = .external_tool_completed },
    .{ .wire = "external_tool.requested", .tag = .external_tool_requested },
    .{ .wire = "factory.run_settled", .tag = .factory_run_settled },
    .{ .wire = "factory.run_started", .tag = .factory_run_started },
    .{ .wire = "factory.run_updated", .tag = .factory_run_updated },
    .{ .wire = "hook.end", .tag = .hook_end },
    .{ .wire = "hook.progress", .tag = .hook_progress },
    .{ .wire = "hook.start", .tag = .hook_start },
    .{ .wire = "mcp.headers_refresh_completed", .tag = .mcp_headers_refresh_completed },
    .{ .wire = "mcp.headers_refresh_required", .tag = .mcp_headers_refresh_required },
    .{ .wire = "mcp.oauth_completed", .tag = .mcp_oauth_completed },
    .{ .wire = "mcp.oauth_required", .tag = .mcp_oauth_required },
    .{ .wire = "mcp.prompts.list_changed", .tag = .mcp_prompts_list_changed },
    .{ .wire = "mcp.resources.list_changed", .tag = .mcp_resources_list_changed },
    .{ .wire = "mcp.tools.list_changed", .tag = .mcp_tools_list_changed },
    .{ .wire = "mcp_app.tool_call_complete", .tag = .mcp_app_tool_call_complete },
    .{ .wire = "model.call_failure", .tag = .model_call_failure },
    .{ .wire = "model.call_finished", .tag = .model_call_finished },
    .{ .wire = "model.call_start", .tag = .model_call_start },
    .{ .wire = "pending_messages.modified", .tag = .pending_messages_modified },
    .{ .wire = "permission.completed", .tag = .permission_completed },
    .{ .wire = "permission.requested", .tag = .permission_requested },
    .{ .wire = "prompt_cache_break", .tag = .prompt_cache_break },
    .{ .wire = "sampling.completed", .tag = .sampling_completed },
    .{ .wire = "sampling.requested", .tag = .sampling_requested },
    .{ .wire = "sandbox.decision", .tag = .sandbox_decision },
    .{ .wire = "session.auto_mode_resolved", .tag = .session_auto_mode_resolved },
    .{ .wire = "session.auto_tier_recommendation", .tag = .session_auto_tier_recommendation },
    .{ .wire = "session.auto_tier_switch_failed", .tag = .session_auto_tier_switch_failed },
    .{ .wire = "session.autopilot_objective_changed", .tag = .session_autopilot_objective_changed },
    .{ .wire = "session.background_tasks_changed", .tag = .session_background_tasks_changed },
    .{ .wire = "session.binary_asset", .tag = .session_binary_asset },
    .{ .wire = "session.canvas.closed", .tag = .session_canvas_closed },
    .{ .wire = "session.canvas.opened", .tag = .session_canvas_opened },
    .{ .wire = "session.canvas.recorded", .tag = .session_canvas_recorded },
    .{ .wire = "session.canvas.registry_changed", .tag = .session_canvas_registry_changed },
    .{ .wire = "session.canvas.removed", .tag = .session_canvas_removed },
    .{ .wire = "session.canvas.unavailable", .tag = .session_canvas_unavailable },
    .{ .wire = "session.compaction_complete", .tag = .session_compaction_complete },
    .{ .wire = "session.compaction_start", .tag = .session_compaction_start },
    .{ .wire = "session.completion_receipt", .tag = .session_completion_receipt },
    .{ .wire = "session.context_changed", .tag = .session_context_changed },
    .{ .wire = "session.context_cleared", .tag = .session_context_cleared },
    .{ .wire = "session.custom_agents_updated", .tag = .session_custom_agents_updated },
    .{ .wire = "session.custom_notification", .tag = .session_custom_notification },
    .{ .wire = "session.error", .tag = .session_error },
    .{ .wire = "session.extensions.attachments_pushed", .tag = .session_extensions_attachments_pushed },
    .{ .wire = "session.extensions_loaded", .tag = .session_extensions_loaded },
    .{ .wire = "session.fusion_commit_started", .tag = .session_fusion_commit_started },
    .{ .wire = "session.fusion_completed", .tag = .session_fusion_completed },
    .{ .wire = "session.fusion_handoff", .tag = .session_fusion_handoff },
    .{ .wire = "session.fusion_resolved", .tag = .session_fusion_resolved },
    .{ .wire = "session.fusion_route_failed", .tag = .session_fusion_route_failed },
    .{ .wire = "session.fusion_route_started", .tag = .session_fusion_route_started },
    .{ .wire = "session.handoff", .tag = .session_handoff },
    .{ .wire = "session.idle", .tag = .session_idle },
    .{ .wire = "session.info", .tag = .session_info },
    .{ .wire = "session.managed_settings_enforced", .tag = .session_managed_settings_enforced },
    .{ .wire = "session.managed_settings_resolved", .tag = .session_managed_settings_resolved },
    .{ .wire = "session.mcp_server_needs_reconnect", .tag = .session_mcp_server_needs_reconnect },
    .{ .wire = "session.mcp_server_removed", .tag = .session_mcp_server_removed },
    .{ .wire = "session.mcp_server_status_changed", .tag = .session_mcp_server_status_changed },
    .{ .wire = "session.mcp_servers_loaded", .tag = .session_mcp_servers_loaded },
    .{ .wire = "session.memory_changed", .tag = .session_memory_changed },
    .{ .wire = "session.mode_changed", .tag = .session_mode_changed },
    .{ .wire = "session.mode_notice_delivered", .tag = .session_mode_notice_delivered },
    .{ .wire = "session.model_change", .tag = .session_model_change },
    .{ .wire = "session.permissions_changed", .tag = .session_permissions_changed },
    .{ .wire = "session.plan_changed", .tag = .session_plan_changed },
    .{ .wire = "session.remote_steerable_changed", .tag = .session_remote_steerable_changed },
    .{ .wire = "session.resume", .tag = .session_resume },
    .{ .wire = "session.schedule_cancelled", .tag = .session_schedule_cancelled },
    .{ .wire = "session.schedule_created", .tag = .session_schedule_created },
    .{ .wire = "session.schedule_rearmed", .tag = .session_schedule_rearmed },
    .{ .wire = "session.session_limits_changed", .tag = .session_session_limits_changed },
    .{ .wire = "session.shutdown", .tag = .session_shutdown },
    .{ .wire = "session.skills_loaded", .tag = .session_skills_loaded },
    .{ .wire = "session.snapshot_rewind", .tag = .session_snapshot_rewind },
    .{ .wire = "session.start", .tag = .session_start },
    .{ .wire = "session.task_complete", .tag = .session_task_complete },
    .{ .wire = "session.title_changed", .tag = .session_title_changed },
    .{ .wire = "session.todos_changed", .tag = .session_todos_changed },
    .{ .wire = "session.tools_updated", .tag = .session_tools_updated },
    .{ .wire = "session.truncation", .tag = .session_truncation },
    .{ .wire = "session.usage_checkpoint", .tag = .session_usage_checkpoint },
    .{ .wire = "session.usage_info", .tag = .session_usage_info },
    .{ .wire = "session.warning", .tag = .session_warning },
    .{ .wire = "session.workspace_file_changed", .tag = .session_workspace_file_changed },
    .{ .wire = "session_limits_exhausted.completed", .tag = .session_limits_exhausted_completed },
    .{ .wire = "session_limits_exhausted.requested", .tag = .session_limits_exhausted_requested },
    .{ .wire = "skill.invoked", .tag = .skill_invoked },
    .{ .wire = "subagent.completed", .tag = .subagent_completed },
    .{ .wire = "subagent.configured", .tag = .subagent_configured },
    .{ .wire = "subagent.deselected", .tag = .subagent_deselected },
    .{ .wire = "subagent.failed", .tag = .subagent_failed },
    .{ .wire = "subagent.selected", .tag = .subagent_selected },
    .{ .wire = "subagent.started", .tag = .subagent_started },
    .{ .wire = "system.message", .tag = .system_message },
    .{ .wire = "system.notification", .tag = .system_notification },
    .{ .wire = "tool.execution_complete", .tag = .tool_execution_complete },
    .{ .wire = "tool.execution_partial_result", .tag = .tool_execution_partial_result },
    .{ .wire = "tool.execution_progress", .tag = .tool_execution_progress },
    .{ .wire = "tool.execution_start", .tag = .tool_execution_start },
    .{ .wire = "tool.user_requested", .tag = .tool_user_requested },
    .{ .wire = "tool_search.activated", .tag = .tool_search_activated },
    .{ .wire = "ui.ephemeral_query", .tag = .ui_ephemeral_query },
    .{ .wire = "user.message", .tag = .user_message },
    .{ .wire = "user_input.completed", .tag = .user_input_completed },
    .{ .wire = "user_input.requested", .tag = .user_input_requested },
};

fn tagFromDiscriminator(wire: []const u8) ?SessionEventTag {
    if (std.mem.eql(u8, wire, "abort")) return .abort;
    if (std.mem.eql(u8, wire, "agent.interrupted")) return .agent_interrupted;
    if (std.mem.eql(u8, wire, "assistant.fusion_phase_activity")) return .assistant_fusion_phase_activity;
    if (std.mem.eql(u8, wire, "assistant.fusion_phase_completed")) return .assistant_fusion_phase_completed;
    if (std.mem.eql(u8, wire, "assistant.fusion_phase_failed")) return .assistant_fusion_phase_failed;
    if (std.mem.eql(u8, wire, "assistant.fusion_phase_started")) return .assistant_fusion_phase_started;
    if (std.mem.eql(u8, wire, "assistant.idle")) return .assistant_idle;
    if (std.mem.eql(u8, wire, "assistant.intent")) return .assistant_intent;
    if (std.mem.eql(u8, wire, "assistant.message")) return .assistant_message;
    if (std.mem.eql(u8, wire, "assistant.message_delta")) return .assistant_message_delta;
    if (std.mem.eql(u8, wire, "assistant.message_start")) return .assistant_message_start;
    if (std.mem.eql(u8, wire, "assistant.reasoning")) return .assistant_reasoning;
    if (std.mem.eql(u8, wire, "assistant.reasoning_delta")) return .assistant_reasoning_delta;
    if (std.mem.eql(u8, wire, "assistant.server_tool_progress")) return .assistant_server_tool_progress;
    if (std.mem.eql(u8, wire, "assistant.streaming_delta")) return .assistant_streaming_delta;
    if (std.mem.eql(u8, wire, "assistant.tool_call_delta")) return .assistant_tool_call_delta;
    if (std.mem.eql(u8, wire, "assistant.turn_end")) return .assistant_turn_end;
    if (std.mem.eql(u8, wire, "assistant.turn_retry")) return .assistant_turn_retry;
    if (std.mem.eql(u8, wire, "assistant.turn_start")) return .assistant_turn_start;
    if (std.mem.eql(u8, wire, "assistant.usage")) return .assistant_usage;
    if (std.mem.eql(u8, wire, "auto_mode_switch.completed")) return .auto_mode_switch_completed;
    if (std.mem.eql(u8, wire, "auto_mode_switch.requested")) return .auto_mode_switch_requested;
    if (std.mem.eql(u8, wire, "capabilities.changed")) return .capabilities_changed;
    if (std.mem.eql(u8, wire, "command.completed")) return .command_completed;
    if (std.mem.eql(u8, wire, "command.execute")) return .command_execute;
    if (std.mem.eql(u8, wire, "command.queued")) return .command_queued;
    if (std.mem.eql(u8, wire, "commands.changed")) return .commands_changed;
    if (std.mem.eql(u8, wire, "elicitation.completed")) return .elicitation_completed;
    if (std.mem.eql(u8, wire, "elicitation.requested")) return .elicitation_requested;
    if (std.mem.eql(u8, wire, "exit_plan_mode.completed")) return .exit_plan_mode_completed;
    if (std.mem.eql(u8, wire, "exit_plan_mode.requested")) return .exit_plan_mode_requested;
    if (std.mem.eql(u8, wire, "external_tool.completed")) return .external_tool_completed;
    if (std.mem.eql(u8, wire, "external_tool.requested")) return .external_tool_requested;
    if (std.mem.eql(u8, wire, "factory.run_settled")) return .factory_run_settled;
    if (std.mem.eql(u8, wire, "factory.run_started")) return .factory_run_started;
    if (std.mem.eql(u8, wire, "factory.run_updated")) return .factory_run_updated;
    if (std.mem.eql(u8, wire, "hook.end")) return .hook_end;
    if (std.mem.eql(u8, wire, "hook.progress")) return .hook_progress;
    if (std.mem.eql(u8, wire, "hook.start")) return .hook_start;
    if (std.mem.eql(u8, wire, "mcp.headers_refresh_completed")) return .mcp_headers_refresh_completed;
    if (std.mem.eql(u8, wire, "mcp.headers_refresh_required")) return .mcp_headers_refresh_required;
    if (std.mem.eql(u8, wire, "mcp.oauth_completed")) return .mcp_oauth_completed;
    if (std.mem.eql(u8, wire, "mcp.oauth_required")) return .mcp_oauth_required;
    if (std.mem.eql(u8, wire, "mcp.prompts.list_changed")) return .mcp_prompts_list_changed;
    if (std.mem.eql(u8, wire, "mcp.resources.list_changed")) return .mcp_resources_list_changed;
    if (std.mem.eql(u8, wire, "mcp.tools.list_changed")) return .mcp_tools_list_changed;
    if (std.mem.eql(u8, wire, "mcp_app.tool_call_complete")) return .mcp_app_tool_call_complete;
    if (std.mem.eql(u8, wire, "model.call_failure")) return .model_call_failure;
    if (std.mem.eql(u8, wire, "model.call_finished")) return .model_call_finished;
    if (std.mem.eql(u8, wire, "model.call_start")) return .model_call_start;
    if (std.mem.eql(u8, wire, "pending_messages.modified")) return .pending_messages_modified;
    if (std.mem.eql(u8, wire, "permission.completed")) return .permission_completed;
    if (std.mem.eql(u8, wire, "permission.requested")) return .permission_requested;
    if (std.mem.eql(u8, wire, "prompt_cache_break")) return .prompt_cache_break;
    if (std.mem.eql(u8, wire, "sampling.completed")) return .sampling_completed;
    if (std.mem.eql(u8, wire, "sampling.requested")) return .sampling_requested;
    if (std.mem.eql(u8, wire, "sandbox.decision")) return .sandbox_decision;
    if (std.mem.eql(u8, wire, "session.auto_mode_resolved")) return .session_auto_mode_resolved;
    if (std.mem.eql(u8, wire, "session.auto_tier_recommendation")) return .session_auto_tier_recommendation;
    if (std.mem.eql(u8, wire, "session.auto_tier_switch_failed")) return .session_auto_tier_switch_failed;
    if (std.mem.eql(u8, wire, "session.autopilot_objective_changed")) return .session_autopilot_objective_changed;
    if (std.mem.eql(u8, wire, "session.background_tasks_changed")) return .session_background_tasks_changed;
    if (std.mem.eql(u8, wire, "session.binary_asset")) return .session_binary_asset;
    if (std.mem.eql(u8, wire, "session.canvas.closed")) return .session_canvas_closed;
    if (std.mem.eql(u8, wire, "session.canvas.opened")) return .session_canvas_opened;
    if (std.mem.eql(u8, wire, "session.canvas.recorded")) return .session_canvas_recorded;
    if (std.mem.eql(u8, wire, "session.canvas.registry_changed")) return .session_canvas_registry_changed;
    if (std.mem.eql(u8, wire, "session.canvas.removed")) return .session_canvas_removed;
    if (std.mem.eql(u8, wire, "session.canvas.unavailable")) return .session_canvas_unavailable;
    if (std.mem.eql(u8, wire, "session.compaction_complete")) return .session_compaction_complete;
    if (std.mem.eql(u8, wire, "session.compaction_start")) return .session_compaction_start;
    if (std.mem.eql(u8, wire, "session.completion_receipt")) return .session_completion_receipt;
    if (std.mem.eql(u8, wire, "session.context_changed")) return .session_context_changed;
    if (std.mem.eql(u8, wire, "session.context_cleared")) return .session_context_cleared;
    if (std.mem.eql(u8, wire, "session.custom_agents_updated")) return .session_custom_agents_updated;
    if (std.mem.eql(u8, wire, "session.custom_notification")) return .session_custom_notification;
    if (std.mem.eql(u8, wire, "session.error")) return .session_error;
    if (std.mem.eql(u8, wire, "session.extensions.attachments_pushed")) return .session_extensions_attachments_pushed;
    if (std.mem.eql(u8, wire, "session.extensions_loaded")) return .session_extensions_loaded;
    if (std.mem.eql(u8, wire, "session.fusion_commit_started")) return .session_fusion_commit_started;
    if (std.mem.eql(u8, wire, "session.fusion_completed")) return .session_fusion_completed;
    if (std.mem.eql(u8, wire, "session.fusion_handoff")) return .session_fusion_handoff;
    if (std.mem.eql(u8, wire, "session.fusion_resolved")) return .session_fusion_resolved;
    if (std.mem.eql(u8, wire, "session.fusion_route_failed")) return .session_fusion_route_failed;
    if (std.mem.eql(u8, wire, "session.fusion_route_started")) return .session_fusion_route_started;
    if (std.mem.eql(u8, wire, "session.handoff")) return .session_handoff;
    if (std.mem.eql(u8, wire, "session.idle")) return .session_idle;
    if (std.mem.eql(u8, wire, "session.info")) return .session_info;
    if (std.mem.eql(u8, wire, "session.managed_settings_enforced")) return .session_managed_settings_enforced;
    if (std.mem.eql(u8, wire, "session.managed_settings_resolved")) return .session_managed_settings_resolved;
    if (std.mem.eql(u8, wire, "session.mcp_server_needs_reconnect")) return .session_mcp_server_needs_reconnect;
    if (std.mem.eql(u8, wire, "session.mcp_server_removed")) return .session_mcp_server_removed;
    if (std.mem.eql(u8, wire, "session.mcp_server_status_changed")) return .session_mcp_server_status_changed;
    if (std.mem.eql(u8, wire, "session.mcp_servers_loaded")) return .session_mcp_servers_loaded;
    if (std.mem.eql(u8, wire, "session.memory_changed")) return .session_memory_changed;
    if (std.mem.eql(u8, wire, "session.mode_changed")) return .session_mode_changed;
    if (std.mem.eql(u8, wire, "session.mode_notice_delivered")) return .session_mode_notice_delivered;
    if (std.mem.eql(u8, wire, "session.model_change")) return .session_model_change;
    if (std.mem.eql(u8, wire, "session.permissions_changed")) return .session_permissions_changed;
    if (std.mem.eql(u8, wire, "session.plan_changed")) return .session_plan_changed;
    if (std.mem.eql(u8, wire, "session.remote_steerable_changed")) return .session_remote_steerable_changed;
    if (std.mem.eql(u8, wire, "session.resume")) return .session_resume;
    if (std.mem.eql(u8, wire, "session.schedule_cancelled")) return .session_schedule_cancelled;
    if (std.mem.eql(u8, wire, "session.schedule_created")) return .session_schedule_created;
    if (std.mem.eql(u8, wire, "session.schedule_rearmed")) return .session_schedule_rearmed;
    if (std.mem.eql(u8, wire, "session.session_limits_changed")) return .session_session_limits_changed;
    if (std.mem.eql(u8, wire, "session.shutdown")) return .session_shutdown;
    if (std.mem.eql(u8, wire, "session.skills_loaded")) return .session_skills_loaded;
    if (std.mem.eql(u8, wire, "session.snapshot_rewind")) return .session_snapshot_rewind;
    if (std.mem.eql(u8, wire, "session.start")) return .session_start;
    if (std.mem.eql(u8, wire, "session.task_complete")) return .session_task_complete;
    if (std.mem.eql(u8, wire, "session.title_changed")) return .session_title_changed;
    if (std.mem.eql(u8, wire, "session.todos_changed")) return .session_todos_changed;
    if (std.mem.eql(u8, wire, "session.tools_updated")) return .session_tools_updated;
    if (std.mem.eql(u8, wire, "session.truncation")) return .session_truncation;
    if (std.mem.eql(u8, wire, "session.usage_checkpoint")) return .session_usage_checkpoint;
    if (std.mem.eql(u8, wire, "session.usage_info")) return .session_usage_info;
    if (std.mem.eql(u8, wire, "session.warning")) return .session_warning;
    if (std.mem.eql(u8, wire, "session.workspace_file_changed")) return .session_workspace_file_changed;
    if (std.mem.eql(u8, wire, "session_limits_exhausted.completed")) return .session_limits_exhausted_completed;
    if (std.mem.eql(u8, wire, "session_limits_exhausted.requested")) return .session_limits_exhausted_requested;
    if (std.mem.eql(u8, wire, "skill.invoked")) return .skill_invoked;
    if (std.mem.eql(u8, wire, "subagent.completed")) return .subagent_completed;
    if (std.mem.eql(u8, wire, "subagent.configured")) return .subagent_configured;
    if (std.mem.eql(u8, wire, "subagent.deselected")) return .subagent_deselected;
    if (std.mem.eql(u8, wire, "subagent.failed")) return .subagent_failed;
    if (std.mem.eql(u8, wire, "subagent.selected")) return .subagent_selected;
    if (std.mem.eql(u8, wire, "subagent.started")) return .subagent_started;
    if (std.mem.eql(u8, wire, "system.message")) return .system_message;
    if (std.mem.eql(u8, wire, "system.notification")) return .system_notification;
    if (std.mem.eql(u8, wire, "tool.execution_complete")) return .tool_execution_complete;
    if (std.mem.eql(u8, wire, "tool.execution_partial_result")) return .tool_execution_partial_result;
    if (std.mem.eql(u8, wire, "tool.execution_progress")) return .tool_execution_progress;
    if (std.mem.eql(u8, wire, "tool.execution_start")) return .tool_execution_start;
    if (std.mem.eql(u8, wire, "tool.user_requested")) return .tool_user_requested;
    if (std.mem.eql(u8, wire, "tool_search.activated")) return .tool_search_activated;
    if (std.mem.eql(u8, wire, "ui.ephemeral_query")) return .ui_ephemeral_query;
    if (std.mem.eql(u8, wire, "user.message")) return .user_message;
    if (std.mem.eql(u8, wire, "user_input.completed")) return .user_input_completed;
    if (std.mem.eql(u8, wire, "user_input.requested")) return .user_input_requested;
    return null;
}

pub fn parseEvent(allocator: std.mem.Allocator, value: std.json.Value) !SessionEvent {
    const object = try payloads.requiredObject(value);
    const wire = try payloads.requiredString(object, "type");
    const data_value: std.json.Value = object.get("data") orelse .{ .object = .empty };
    const data = try payloads.requiredObject(data_value);

    var raw = try payloads.ownRawData(allocator, data_value);
    errdefer raw.deinit(allocator);

    const tag = tagFromDiscriminator(wire) orelse {
        const owned_wire = try allocator.dupe(u8, wire);
        errdefer allocator.free(owned_wire);
        return .{ .unknown = .{
            .event_type = owned_wire,
            .data_json = raw.take().data_json,
        } };
    };

    switch (tag) {
        .abort => return .{ .abort = raw.take() },
        .agent_interrupted => return .{ .agent_interrupted = raw.take() },
        .assistant_fusion_phase_activity => return .{ .assistant_fusion_phase_activity = raw.take() },
        .assistant_fusion_phase_completed => return .{ .assistant_fusion_phase_completed = raw.take() },
        .assistant_fusion_phase_failed => return .{ .assistant_fusion_phase_failed = raw.take() },
        .assistant_fusion_phase_started => return .{ .assistant_fusion_phase_started = raw.take() },
        .assistant_idle => return .{ .assistant_idle = raw.take() },
        .assistant_intent => return .{ .assistant_intent = raw.take() },
        .assistant_message => {
            var payload = try payloads.parseAssistantMessage(allocator, data);
            payload.raw = raw.take();
            return .{ .assistant_message = payload };
        },
        .assistant_message_delta => {
            var payload = try payloads.parseAssistantMessageDelta(allocator, data);
            payload.raw = raw.take();
            return .{ .assistant_message_delta = payload };
        },
        .assistant_message_start => return .{ .assistant_message_start = raw.take() },
        .assistant_reasoning => {
            var payload = try payloads.parseAssistantReasoning(allocator, data);
            payload.raw = raw.take();
            return .{ .assistant_reasoning = payload };
        },
        .assistant_reasoning_delta => {
            var payload = try payloads.parseAssistantReasoningDelta(allocator, data);
            payload.raw = raw.take();
            return .{ .assistant_reasoning_delta = payload };
        },
        .assistant_server_tool_progress => return .{ .assistant_server_tool_progress = raw.take() },
        .assistant_streaming_delta => return .{ .assistant_streaming_delta = raw.take() },
        .assistant_tool_call_delta => return .{ .assistant_tool_call_delta = raw.take() },
        .assistant_turn_end => return .{ .assistant_turn_end = raw.take() },
        .assistant_turn_retry => return .{ .assistant_turn_retry = raw.take() },
        .assistant_turn_start => return .{ .assistant_turn_start = raw.take() },
        .assistant_usage => return .{ .assistant_usage = raw.take() },
        .auto_mode_switch_completed => return .{ .auto_mode_switch_completed = raw.take() },
        .auto_mode_switch_requested => return .{ .auto_mode_switch_requested = raw.take() },
        .capabilities_changed => return .{ .capabilities_changed = raw.take() },
        .command_completed => return .{ .command_completed = raw.take() },
        .command_execute => return .{ .command_execute = raw.take() },
        .command_queued => return .{ .command_queued = raw.take() },
        .commands_changed => return .{ .commands_changed = raw.take() },
        .elicitation_completed => return .{ .elicitation_completed = raw.take() },
        .elicitation_requested => return .{ .elicitation_requested = raw.take() },
        .exit_plan_mode_completed => return .{ .exit_plan_mode_completed = raw.take() },
        .exit_plan_mode_requested => return .{ .exit_plan_mode_requested = raw.take() },
        .external_tool_completed => return .{ .external_tool_completed = raw.take() },
        .external_tool_requested => {
            var payload = try payloads.parseExternalToolRequested(allocator, data);
            payload.raw = raw.take();
            return .{ .external_tool_requested = payload };
        },
        .factory_run_settled => return .{ .factory_run_settled = raw.take() },
        .factory_run_started => return .{ .factory_run_started = raw.take() },
        .factory_run_updated => return .{ .factory_run_updated = raw.take() },
        .hook_end => return .{ .hook_end = raw.take() },
        .hook_progress => return .{ .hook_progress = raw.take() },
        .hook_start => return .{ .hook_start = raw.take() },
        .mcp_headers_refresh_completed => return .{ .mcp_headers_refresh_completed = raw.take() },
        .mcp_headers_refresh_required => return .{ .mcp_headers_refresh_required = raw.take() },
        .mcp_oauth_completed => return .{ .mcp_oauth_completed = raw.take() },
        .mcp_oauth_required => return .{ .mcp_oauth_required = raw.take() },
        .mcp_prompts_list_changed => return .{ .mcp_prompts_list_changed = raw.take() },
        .mcp_resources_list_changed => return .{ .mcp_resources_list_changed = raw.take() },
        .mcp_tools_list_changed => return .{ .mcp_tools_list_changed = raw.take() },
        .mcp_app_tool_call_complete => return .{ .mcp_app_tool_call_complete = raw.take() },
        .model_call_failure => return .{ .model_call_failure = raw.take() },
        .model_call_finished => return .{ .model_call_finished = raw.take() },
        .model_call_start => return .{ .model_call_start = raw.take() },
        .pending_messages_modified => return .{ .pending_messages_modified = raw.take() },
        .permission_completed => return .{ .permission_completed = raw.take() },
        .permission_requested => {
            var payload = try payloads.parsePermissionRequested(allocator, data);
            payload.raw = raw.take();
            return .{ .permission_requested = payload };
        },
        .prompt_cache_break => return .{ .prompt_cache_break = raw.take() },
        .sampling_completed => return .{ .sampling_completed = raw.take() },
        .sampling_requested => return .{ .sampling_requested = raw.take() },
        .sandbox_decision => return .{ .sandbox_decision = raw.take() },
        .session_auto_mode_resolved => return .{ .session_auto_mode_resolved = raw.take() },
        .session_auto_tier_recommendation => return .{ .session_auto_tier_recommendation = raw.take() },
        .session_auto_tier_switch_failed => return .{ .session_auto_tier_switch_failed = raw.take() },
        .session_autopilot_objective_changed => return .{ .session_autopilot_objective_changed = raw.take() },
        .session_background_tasks_changed => return .{ .session_background_tasks_changed = raw.take() },
        .session_binary_asset => return .{ .session_binary_asset = raw.take() },
        .session_canvas_closed => return .{ .session_canvas_closed = raw.take() },
        .session_canvas_opened => return .{ .session_canvas_opened = raw.take() },
        .session_canvas_recorded => return .{ .session_canvas_recorded = raw.take() },
        .session_canvas_registry_changed => return .{ .session_canvas_registry_changed = raw.take() },
        .session_canvas_removed => return .{ .session_canvas_removed = raw.take() },
        .session_canvas_unavailable => return .{ .session_canvas_unavailable = raw.take() },
        .session_compaction_complete => return .{ .session_compaction_complete = raw.take() },
        .session_compaction_start => return .{ .session_compaction_start = raw.take() },
        .session_completion_receipt => return .{ .session_completion_receipt = raw.take() },
        .session_context_changed => return .{ .session_context_changed = raw.take() },
        .session_context_cleared => return .{ .session_context_cleared = raw.take() },
        .session_custom_agents_updated => return .{ .session_custom_agents_updated = raw.take() },
        .session_custom_notification => return .{ .session_custom_notification = raw.take() },
        .session_error => {
            var payload = try payloads.parseSessionError(allocator, data);
            payload.raw = raw.take();
            return .{ .session_error = payload };
        },
        .session_extensions_attachments_pushed => return .{ .session_extensions_attachments_pushed = raw.take() },
        .session_extensions_loaded => return .{ .session_extensions_loaded = raw.take() },
        .session_fusion_commit_started => return .{ .session_fusion_commit_started = raw.take() },
        .session_fusion_completed => return .{ .session_fusion_completed = raw.take() },
        .session_fusion_handoff => return .{ .session_fusion_handoff = raw.take() },
        .session_fusion_resolved => return .{ .session_fusion_resolved = raw.take() },
        .session_fusion_route_failed => return .{ .session_fusion_route_failed = raw.take() },
        .session_fusion_route_started => return .{ .session_fusion_route_started = raw.take() },
        .session_handoff => return .{ .session_handoff = raw.take() },
        .session_idle => {
            var payload = try payloads.parseSessionIdle(allocator, data);
            payload.raw = raw.take();
            return .{ .session_idle = payload };
        },
        .session_info => return .{ .session_info = raw.take() },
        .session_managed_settings_enforced => return .{ .session_managed_settings_enforced = raw.take() },
        .session_managed_settings_resolved => return .{ .session_managed_settings_resolved = raw.take() },
        .session_mcp_server_needs_reconnect => return .{ .session_mcp_server_needs_reconnect = raw.take() },
        .session_mcp_server_removed => return .{ .session_mcp_server_removed = raw.take() },
        .session_mcp_server_status_changed => return .{ .session_mcp_server_status_changed = raw.take() },
        .session_mcp_servers_loaded => return .{ .session_mcp_servers_loaded = raw.take() },
        .session_memory_changed => return .{ .session_memory_changed = raw.take() },
        .session_mode_changed => return .{ .session_mode_changed = raw.take() },
        .session_mode_notice_delivered => return .{ .session_mode_notice_delivered = raw.take() },
        .session_model_change => return .{ .session_model_change = raw.take() },
        .session_permissions_changed => return .{ .session_permissions_changed = raw.take() },
        .session_plan_changed => return .{ .session_plan_changed = raw.take() },
        .session_remote_steerable_changed => return .{ .session_remote_steerable_changed = raw.take() },
        .session_resume => return .{ .session_resume = raw.take() },
        .session_schedule_cancelled => return .{ .session_schedule_cancelled = raw.take() },
        .session_schedule_created => return .{ .session_schedule_created = raw.take() },
        .session_schedule_rearmed => return .{ .session_schedule_rearmed = raw.take() },
        .session_session_limits_changed => return .{ .session_session_limits_changed = raw.take() },
        .session_shutdown => return .{ .session_shutdown = raw.take() },
        .session_skills_loaded => return .{ .session_skills_loaded = raw.take() },
        .session_snapshot_rewind => return .{ .session_snapshot_rewind = raw.take() },
        .session_start => return .{ .session_start = raw.take() },
        .session_task_complete => return .{ .session_task_complete = raw.take() },
        .session_title_changed => return .{ .session_title_changed = raw.take() },
        .session_todos_changed => return .{ .session_todos_changed = raw.take() },
        .session_tools_updated => return .{ .session_tools_updated = raw.take() },
        .session_truncation => return .{ .session_truncation = raw.take() },
        .session_usage_checkpoint => return .{ .session_usage_checkpoint = raw.take() },
        .session_usage_info => return .{ .session_usage_info = raw.take() },
        .session_warning => return .{ .session_warning = raw.take() },
        .session_workspace_file_changed => return .{ .session_workspace_file_changed = raw.take() },
        .session_limits_exhausted_completed => return .{ .session_limits_exhausted_completed = raw.take() },
        .session_limits_exhausted_requested => return .{ .session_limits_exhausted_requested = raw.take() },
        .skill_invoked => return .{ .skill_invoked = raw.take() },
        .subagent_completed => return .{ .subagent_completed = raw.take() },
        .subagent_configured => return .{ .subagent_configured = raw.take() },
        .subagent_deselected => return .{ .subagent_deselected = raw.take() },
        .subagent_failed => return .{ .subagent_failed = raw.take() },
        .subagent_selected => return .{ .subagent_selected = raw.take() },
        .subagent_started => return .{ .subagent_started = raw.take() },
        .system_message => return .{ .system_message = raw.take() },
        .system_notification => return .{ .system_notification = raw.take() },
        .tool_execution_complete => return .{ .tool_execution_complete = raw.take() },
        .tool_execution_partial_result => return .{ .tool_execution_partial_result = raw.take() },
        .tool_execution_progress => return .{ .tool_execution_progress = raw.take() },
        .tool_execution_start => return .{ .tool_execution_start = raw.take() },
        .tool_user_requested => return .{ .tool_user_requested = raw.take() },
        .tool_search_activated => return .{ .tool_search_activated = raw.take() },
        .ui_ephemeral_query => return .{ .ui_ephemeral_query = raw.take() },
        .user_message => return .{ .user_message = raw.take() },
        .user_input_completed => return .{ .user_input_completed = raw.take() },
        .user_input_requested => return .{ .user_input_requested = raw.take() },
        .unknown => unreachable,
    }
}

const EventSample = struct {
    json: []const u8,
    tag: SessionEventTag,
};

const pinned_event_samples = [_]EventSample{
    .{ .json = "{\"type\":\"abort\",\"data\":{}}", .tag = .abort },
    .{ .json = "{\"type\":\"agent.interrupted\",\"data\":{}}", .tag = .agent_interrupted },
    .{ .json = "{\"type\":\"assistant.fusion_phase_activity\",\"data\":{}}", .tag = .assistant_fusion_phase_activity },
    .{ .json = "{\"type\":\"assistant.fusion_phase_completed\",\"data\":{}}", .tag = .assistant_fusion_phase_completed },
    .{ .json = "{\"type\":\"assistant.fusion_phase_failed\",\"data\":{}}", .tag = .assistant_fusion_phase_failed },
    .{ .json = "{\"type\":\"assistant.fusion_phase_started\",\"data\":{}}", .tag = .assistant_fusion_phase_started },
    .{ .json = "{\"type\":\"assistant.idle\",\"data\":{}}", .tag = .assistant_idle },
    .{ .json = "{\"type\":\"assistant.intent\",\"data\":{}}", .tag = .assistant_intent },
    .{ .json = "{\"type\":\"assistant.message\",\"data\":{\"content\":\"hello\",\"messageId\":\"message-1\"}}", .tag = .assistant_message },
    .{ .json = "{\"type\":\"assistant.message_delta\",\"data\":{\"deltaContent\":\"hello\",\"messageId\":\"message-1\"}}", .tag = .assistant_message_delta },
    .{ .json = "{\"type\":\"assistant.message_start\",\"data\":{}}", .tag = .assistant_message_start },
    .{ .json = "{\"type\":\"assistant.reasoning\",\"data\":{\"reasoningId\":\"reasoning-1\",\"content\":\"inspect\",\"rte\":true}}", .tag = .assistant_reasoning },
    .{ .json = "{\"type\":\"assistant.reasoning_delta\",\"data\":{\"reasoningId\":\"reasoning-1\",\"deltaContent\":\"inspect\"}}", .tag = .assistant_reasoning_delta },
    .{ .json = "{\"type\":\"assistant.server_tool_progress\",\"data\":{}}", .tag = .assistant_server_tool_progress },
    .{ .json = "{\"type\":\"assistant.streaming_delta\",\"data\":{}}", .tag = .assistant_streaming_delta },
    .{ .json = "{\"type\":\"assistant.tool_call_delta\",\"data\":{}}", .tag = .assistant_tool_call_delta },
    .{ .json = "{\"type\":\"assistant.turn_end\",\"data\":{}}", .tag = .assistant_turn_end },
    .{ .json = "{\"type\":\"assistant.turn_retry\",\"data\":{}}", .tag = .assistant_turn_retry },
    .{ .json = "{\"type\":\"assistant.turn_start\",\"data\":{}}", .tag = .assistant_turn_start },
    .{ .json = "{\"type\":\"assistant.usage\",\"data\":{}}", .tag = .assistant_usage },
    .{ .json = "{\"type\":\"auto_mode_switch.completed\",\"data\":{}}", .tag = .auto_mode_switch_completed },
    .{ .json = "{\"type\":\"auto_mode_switch.requested\",\"data\":{}}", .tag = .auto_mode_switch_requested },
    .{ .json = "{\"type\":\"capabilities.changed\",\"data\":{}}", .tag = .capabilities_changed },
    .{ .json = "{\"type\":\"command.completed\",\"data\":{}}", .tag = .command_completed },
    .{ .json = "{\"type\":\"command.execute\",\"data\":{}}", .tag = .command_execute },
    .{ .json = "{\"type\":\"command.queued\",\"data\":{}}", .tag = .command_queued },
    .{ .json = "{\"type\":\"commands.changed\",\"data\":{}}", .tag = .commands_changed },
    .{ .json = "{\"type\":\"elicitation.completed\",\"data\":{}}", .tag = .elicitation_completed },
    .{ .json = "{\"type\":\"elicitation.requested\",\"data\":{}}", .tag = .elicitation_requested },
    .{ .json = "{\"type\":\"exit_plan_mode.completed\",\"data\":{}}", .tag = .exit_plan_mode_completed },
    .{ .json = "{\"type\":\"exit_plan_mode.requested\",\"data\":{}}", .tag = .exit_plan_mode_requested },
    .{ .json = "{\"type\":\"external_tool.completed\",\"data\":{}}", .tag = .external_tool_completed },
    .{ .json = "{\"type\":\"external_tool.requested\",\"data\":{\"requestId\":\"request-1\",\"toolCallId\":\"tool-call-1\",\"toolName\":\"lookup\",\"arguments\":{\"id\":\"alpha\"}}}", .tag = .external_tool_requested },
    .{ .json = "{\"type\":\"factory.run_settled\",\"data\":{}}", .tag = .factory_run_settled },
    .{ .json = "{\"type\":\"factory.run_started\",\"data\":{}}", .tag = .factory_run_started },
    .{ .json = "{\"type\":\"factory.run_updated\",\"data\":{}}", .tag = .factory_run_updated },
    .{ .json = "{\"type\":\"hook.end\",\"data\":{}}", .tag = .hook_end },
    .{ .json = "{\"type\":\"hook.progress\",\"data\":{}}", .tag = .hook_progress },
    .{ .json = "{\"type\":\"hook.start\",\"data\":{}}", .tag = .hook_start },
    .{ .json = "{\"type\":\"mcp.headers_refresh_completed\",\"data\":{}}", .tag = .mcp_headers_refresh_completed },
    .{ .json = "{\"type\":\"mcp.headers_refresh_required\",\"data\":{}}", .tag = .mcp_headers_refresh_required },
    .{ .json = "{\"type\":\"mcp.oauth_completed\",\"data\":{}}", .tag = .mcp_oauth_completed },
    .{ .json = "{\"type\":\"mcp.oauth_required\",\"data\":{}}", .tag = .mcp_oauth_required },
    .{ .json = "{\"type\":\"mcp.prompts.list_changed\",\"data\":{}}", .tag = .mcp_prompts_list_changed },
    .{ .json = "{\"type\":\"mcp.resources.list_changed\",\"data\":{}}", .tag = .mcp_resources_list_changed },
    .{ .json = "{\"type\":\"mcp.tools.list_changed\",\"data\":{}}", .tag = .mcp_tools_list_changed },
    .{ .json = "{\"type\":\"mcp_app.tool_call_complete\",\"data\":{}}", .tag = .mcp_app_tool_call_complete },
    .{ .json = "{\"type\":\"model.call_failure\",\"data\":{}}", .tag = .model_call_failure },
    .{ .json = "{\"type\":\"model.call_finished\",\"data\":{}}", .tag = .model_call_finished },
    .{ .json = "{\"type\":\"model.call_start\",\"data\":{}}", .tag = .model_call_start },
    .{ .json = "{\"type\":\"pending_messages.modified\",\"data\":{}}", .tag = .pending_messages_modified },
    .{ .json = "{\"type\":\"permission.completed\",\"data\":{}}", .tag = .permission_completed },
    .{ .json = "{\"type\":\"permission.requested\",\"data\":{\"requestId\":\"permission-1\",\"permissionRequest\":{\"kind\":\"shell\"}}}", .tag = .permission_requested },
    .{ .json = "{\"type\":\"prompt_cache_break\",\"data\":{}}", .tag = .prompt_cache_break },
    .{ .json = "{\"type\":\"sampling.completed\",\"data\":{}}", .tag = .sampling_completed },
    .{ .json = "{\"type\":\"sampling.requested\",\"data\":{}}", .tag = .sampling_requested },
    .{ .json = "{\"type\":\"sandbox.decision\",\"data\":{}}", .tag = .sandbox_decision },
    .{ .json = "{\"type\":\"session.auto_mode_resolved\",\"data\":{}}", .tag = .session_auto_mode_resolved },
    .{ .json = "{\"type\":\"session.auto_tier_recommendation\",\"data\":{}}", .tag = .session_auto_tier_recommendation },
    .{ .json = "{\"type\":\"session.auto_tier_switch_failed\",\"data\":{}}", .tag = .session_auto_tier_switch_failed },
    .{ .json = "{\"type\":\"session.autopilot_objective_changed\",\"data\":{}}", .tag = .session_autopilot_objective_changed },
    .{ .json = "{\"type\":\"session.background_tasks_changed\",\"data\":{}}", .tag = .session_background_tasks_changed },
    .{ .json = "{\"type\":\"session.binary_asset\",\"data\":{}}", .tag = .session_binary_asset },
    .{ .json = "{\"type\":\"session.canvas.closed\",\"data\":{}}", .tag = .session_canvas_closed },
    .{ .json = "{\"type\":\"session.canvas.opened\",\"data\":{}}", .tag = .session_canvas_opened },
    .{ .json = "{\"type\":\"session.canvas.recorded\",\"data\":{}}", .tag = .session_canvas_recorded },
    .{ .json = "{\"type\":\"session.canvas.registry_changed\",\"data\":{}}", .tag = .session_canvas_registry_changed },
    .{ .json = "{\"type\":\"session.canvas.removed\",\"data\":{}}", .tag = .session_canvas_removed },
    .{ .json = "{\"type\":\"session.canvas.unavailable\",\"data\":{}}", .tag = .session_canvas_unavailable },
    .{ .json = "{\"type\":\"session.compaction_complete\",\"data\":{}}", .tag = .session_compaction_complete },
    .{ .json = "{\"type\":\"session.compaction_start\",\"data\":{}}", .tag = .session_compaction_start },
    .{ .json = "{\"type\":\"session.completion_receipt\",\"data\":{}}", .tag = .session_completion_receipt },
    .{ .json = "{\"type\":\"session.context_changed\",\"data\":{}}", .tag = .session_context_changed },
    .{ .json = "{\"type\":\"session.context_cleared\",\"data\":{}}", .tag = .session_context_cleared },
    .{ .json = "{\"type\":\"session.custom_agents_updated\",\"data\":{}}", .tag = .session_custom_agents_updated },
    .{ .json = "{\"type\":\"session.custom_notification\",\"data\":{}}", .tag = .session_custom_notification },
    .{ .json = "{\"type\":\"session.error\",\"data\":{\"message\":\"failed\"}}", .tag = .session_error },
    .{ .json = "{\"type\":\"session.extensions.attachments_pushed\",\"data\":{}}", .tag = .session_extensions_attachments_pushed },
    .{ .json = "{\"type\":\"session.extensions_loaded\",\"data\":{}}", .tag = .session_extensions_loaded },
    .{ .json = "{\"type\":\"session.fusion_commit_started\",\"data\":{}}", .tag = .session_fusion_commit_started },
    .{ .json = "{\"type\":\"session.fusion_completed\",\"data\":{}}", .tag = .session_fusion_completed },
    .{ .json = "{\"type\":\"session.fusion_handoff\",\"data\":{}}", .tag = .session_fusion_handoff },
    .{ .json = "{\"type\":\"session.fusion_resolved\",\"data\":{}}", .tag = .session_fusion_resolved },
    .{ .json = "{\"type\":\"session.fusion_route_failed\",\"data\":{}}", .tag = .session_fusion_route_failed },
    .{ .json = "{\"type\":\"session.fusion_route_started\",\"data\":{}}", .tag = .session_fusion_route_started },
    .{ .json = "{\"type\":\"session.handoff\",\"data\":{}}", .tag = .session_handoff },
    .{ .json = "{\"type\":\"session.idle\",\"data\":{\"aborted\":false,\"mode\":\"interactive\"}}", .tag = .session_idle },
    .{ .json = "{\"type\":\"session.info\",\"data\":{}}", .tag = .session_info },
    .{ .json = "{\"type\":\"session.managed_settings_enforced\",\"data\":{}}", .tag = .session_managed_settings_enforced },
    .{ .json = "{\"type\":\"session.managed_settings_resolved\",\"data\":{}}", .tag = .session_managed_settings_resolved },
    .{ .json = "{\"type\":\"session.mcp_server_needs_reconnect\",\"data\":{}}", .tag = .session_mcp_server_needs_reconnect },
    .{ .json = "{\"type\":\"session.mcp_server_removed\",\"data\":{}}", .tag = .session_mcp_server_removed },
    .{ .json = "{\"type\":\"session.mcp_server_status_changed\",\"data\":{}}", .tag = .session_mcp_server_status_changed },
    .{ .json = "{\"type\":\"session.mcp_servers_loaded\",\"data\":{}}", .tag = .session_mcp_servers_loaded },
    .{ .json = "{\"type\":\"session.memory_changed\",\"data\":{}}", .tag = .session_memory_changed },
    .{ .json = "{\"type\":\"session.mode_changed\",\"data\":{}}", .tag = .session_mode_changed },
    .{ .json = "{\"type\":\"session.mode_notice_delivered\",\"data\":{}}", .tag = .session_mode_notice_delivered },
    .{ .json = "{\"type\":\"session.model_change\",\"data\":{}}", .tag = .session_model_change },
    .{ .json = "{\"type\":\"session.permissions_changed\",\"data\":{}}", .tag = .session_permissions_changed },
    .{ .json = "{\"type\":\"session.plan_changed\",\"data\":{}}", .tag = .session_plan_changed },
    .{ .json = "{\"type\":\"session.remote_steerable_changed\",\"data\":{}}", .tag = .session_remote_steerable_changed },
    .{ .json = "{\"type\":\"session.resume\",\"data\":{}}", .tag = .session_resume },
    .{ .json = "{\"type\":\"session.schedule_cancelled\",\"data\":{}}", .tag = .session_schedule_cancelled },
    .{ .json = "{\"type\":\"session.schedule_created\",\"data\":{}}", .tag = .session_schedule_created },
    .{ .json = "{\"type\":\"session.schedule_rearmed\",\"data\":{}}", .tag = .session_schedule_rearmed },
    .{ .json = "{\"type\":\"session.session_limits_changed\",\"data\":{}}", .tag = .session_session_limits_changed },
    .{ .json = "{\"type\":\"session.shutdown\",\"data\":{}}", .tag = .session_shutdown },
    .{ .json = "{\"type\":\"session.skills_loaded\",\"data\":{}}", .tag = .session_skills_loaded },
    .{ .json = "{\"type\":\"session.snapshot_rewind\",\"data\":{}}", .tag = .session_snapshot_rewind },
    .{ .json = "{\"type\":\"session.start\",\"data\":{}}", .tag = .session_start },
    .{ .json = "{\"type\":\"session.task_complete\",\"data\":{}}", .tag = .session_task_complete },
    .{ .json = "{\"type\":\"session.title_changed\",\"data\":{}}", .tag = .session_title_changed },
    .{ .json = "{\"type\":\"session.todos_changed\",\"data\":{}}", .tag = .session_todos_changed },
    .{ .json = "{\"type\":\"session.tools_updated\",\"data\":{}}", .tag = .session_tools_updated },
    .{ .json = "{\"type\":\"session.truncation\",\"data\":{}}", .tag = .session_truncation },
    .{ .json = "{\"type\":\"session.usage_checkpoint\",\"data\":{}}", .tag = .session_usage_checkpoint },
    .{ .json = "{\"type\":\"session.usage_info\",\"data\":{}}", .tag = .session_usage_info },
    .{ .json = "{\"type\":\"session.warning\",\"data\":{}}", .tag = .session_warning },
    .{ .json = "{\"type\":\"session.workspace_file_changed\",\"data\":{}}", .tag = .session_workspace_file_changed },
    .{ .json = "{\"type\":\"session_limits_exhausted.completed\",\"data\":{}}", .tag = .session_limits_exhausted_completed },
    .{ .json = "{\"type\":\"session_limits_exhausted.requested\",\"data\":{}}", .tag = .session_limits_exhausted_requested },
    .{ .json = "{\"type\":\"skill.invoked\",\"data\":{}}", .tag = .skill_invoked },
    .{ .json = "{\"type\":\"subagent.completed\",\"data\":{}}", .tag = .subagent_completed },
    .{ .json = "{\"type\":\"subagent.configured\",\"data\":{}}", .tag = .subagent_configured },
    .{ .json = "{\"type\":\"subagent.deselected\",\"data\":{}}", .tag = .subagent_deselected },
    .{ .json = "{\"type\":\"subagent.failed\",\"data\":{}}", .tag = .subagent_failed },
    .{ .json = "{\"type\":\"subagent.selected\",\"data\":{}}", .tag = .subagent_selected },
    .{ .json = "{\"type\":\"subagent.started\",\"data\":{}}", .tag = .subagent_started },
    .{ .json = "{\"type\":\"system.message\",\"data\":{}}", .tag = .system_message },
    .{ .json = "{\"type\":\"system.notification\",\"data\":{}}", .tag = .system_notification },
    .{ .json = "{\"type\":\"tool.execution_complete\",\"data\":{}}", .tag = .tool_execution_complete },
    .{ .json = "{\"type\":\"tool.execution_partial_result\",\"data\":{}}", .tag = .tool_execution_partial_result },
    .{ .json = "{\"type\":\"tool.execution_progress\",\"data\":{}}", .tag = .tool_execution_progress },
    .{ .json = "{\"type\":\"tool.execution_start\",\"data\":{}}", .tag = .tool_execution_start },
    .{ .json = "{\"type\":\"tool.user_requested\",\"data\":{}}", .tag = .tool_user_requested },
    .{ .json = "{\"type\":\"tool_search.activated\",\"data\":{}}", .tag = .tool_search_activated },
    .{ .json = "{\"type\":\"ui.ephemeral_query\",\"data\":{}}", .tag = .ui_ephemeral_query },
    .{ .json = "{\"type\":\"user.message\",\"data\":{}}", .tag = .user_message },
    .{ .json = "{\"type\":\"user_input.completed\",\"data\":{}}", .tag = .user_input_completed },
    .{ .json = "{\"type\":\"user_input.requested\",\"data\":{}}", .tag = .user_input_requested },
};

test "every pinned discriminator parses to its explicit tag" {
    const allocator = std.testing.allocator;
    try std.testing.expectEqual(@as(usize, 140), pinned_event_samples.len);
    for (pinned_event_samples) |sample| {
        const parsed = try std.json.parseFromSlice(std.json.Value, allocator, sample.json, .{});
        defer parsed.deinit();
        var event = try parseEvent(allocator, parsed.value);
        defer event.deinit(allocator);
        try std.testing.expectEqual(sample.tag, std.meta.activeTag(event));
        try std.testing.expectEqualStrings(
            pinned_discriminators[@intFromEnum(sample.tag)].wire,
            event.eventType(),
        );
    }
}

const malformed_rich_event_samples = [_][]const u8{
    "{\"type\":\"assistant.message\",\"data\":{\"messageId\":\"message-1\"}}",
    "{\"type\":\"assistant.message_delta\",\"data\":{\"deltaContent\":\"hello\"}}",
    "{\"type\":\"assistant.reasoning\",\"data\":{\"reasoningId\":\"reasoning-1\"}}",
    "{\"type\":\"assistant.reasoning_delta\",\"data\":{\"reasoningId\":\"reasoning-1\"}}",
    "{\"type\":\"external_tool.requested\",\"data\":{\"requestId\":\"request-1\"}}",
    "{\"type\":\"permission.requested\",\"data\":{\"requestId\":\"permission-1\"}}",
    "{\"type\":\"session.error\",\"data\":{}}",
    "{\"type\":\"session.idle\",\"data\":{\"aborted\":\"false\"}}",
};

test "every malformed rich event returns an error" {
    const allocator = std.testing.allocator;
    for (malformed_rich_event_samples) |sample| {
        const parsed = try std.json.parseFromSlice(std.json.Value, allocator, sample, .{});
        defer parsed.deinit();
        try std.testing.expectError(
            error.InvalidSessionEvent,
            parseEvent(allocator, parsed.value),
        );
    }
}
